#! /usr/bin/bash

DESCRIPTION="Puts candidates screener for stocks"
echo "${0}: $DESCRIPTION"

nohup firefox "https://finviz.com/screener.ashx?v=141&f=cap_smallover,sh_opt_option,sh_price_o5,ta_perf_1wdown,ta_perf2_13w50u&o=perf4w" >/dev/null 2>&1 &
