#! /usr/bin/python

import os
import sys
from operator import itemgetter

from subprocess import call

call(["clear"])

call([ "more", os.path.join(os.environ["HOME"] , "Projects", "TODO") ])

sys.stdin.readline()

files = []
for dirent in os.listdir("."):
    if os.path.isdir(dirent):
        continue
    else:
        files.append(dirent)

filesLines = []
for fn in files:
    data = open(fn, "r").read()
    lines = data.count(os.linesep) + 1
    filesLines.append( { 'lines':lines, 'file':fn } )

sortedFiles = sorted( filesLines, key=itemgetter('lines') )

cmd = ["vi", "-R"]
for lf in sortedFiles:
    cmd.append(lf['file'])

call(cmd)
