#! /usr/bin/bash

while [ : ]
do

    lsof | grep -v grep | egrep -i 'youtube' | awk '{print $2}' | xargs renice -n 15

    lsof | grep -v grep | egrep -i 'youtube' | awk '{print $2}' | xargs chrt -i


    sleep 10

done
